### ISSUE TITLE
PCE/TG16 not listed in the application

### ISSUE THREAD

**Issue by TripHazzard** [silverlays/NoIntro-Roms-Downloader#22]
The Readme says this set can be downloaded via the application but it's not listed in the application itself.

![image](https://github.com/silverlays/NoIntro-Roms-Downloader/assets/41355492/11361cd0-c478-4af6-a2c0-775684cf2530)

**Comment by silverlays** [comment]
You're absolutely right, it's an omission on my part when converting from v1 to v2. This has now been corrected and the new executable is online in the [RELEASES](https://github.com/silverlays/NoIntro-Roms-Downloader/releases/tag/v2.0-RC1).

If you could give feedback if everything looks good to you, it would be greatly appreciated. 🙂

**Comment by TripHazzard** [comment]
Seems to be fixed. Thanks!
